# string templates

QUESTIONS = [
  'Are you suffering from {}?',
  'Are you plagued by {}?',
  'Is {} keeping you up at night?',
  'Worried you might have {}?',
  'You don\'t have to deal with {} alone.',
]

ANSWERS = [
    u'Ask your doctor about {}\u00AE today!',
    u'Try {}\u00AE!',
    u'{}\u00AE can help!',
    u'Ask your doctor if {}\u00AE is right for you!',
]

COMPLIMENTS = [
  "BELIEVE IN YOURSELF",
   "KEEP GOIN !!!!!",
   "HEY! KEEP ON GOING !!!!",
   "YOUVE GOT WHAT IT TAKES !!!",
   "YOUVE COME SO FAR !!!",
   "SMILE =)",
   "SENDING YA LUV SO KEEP GOING",
   "YOURE DOING GREAT",
   "TRUST YOUR UNIQUE PROCESS",
   "DONT CHANGE FOR ANYBODY",
   "EVERYTHING HAPPENS FOR A REASON",
   "DONT GIVE UP",
   "YOU ARE AWESOME",
   "YOU ARE ACCOMPLISHING SO MANY GREAT THINGS",
   "NO ONE CAN REPLICATE YOUR JOURNEY",
   "THIS JOURNEY WAS CURATED JUST FOR YOU AND ONLY YOU",
   "DONT CHANGE FOR ANYONE",
   "KEEP GOOOOOOOOOING",
   "I HOPE YOU KNOW YOU ARE ICONIC",
   "YOU ARE ON THE RIGHT TRACK",
   "YOUR LIFE IS YOUR RESPONSIBILITY AND NO ONE ELSES",
   "WE CAN LEARN AND GROW FROM EACH OTHER",
   "THIS JOURNEY WAS SPECIALLY CURATED FOR JUST YOU",
   "YOU. ARE. A. QUEEN.",
   "YOU ARE NOT ALONE",
   "STAY STRONG",
   "STAY EMPOWERED",
   "EMBRACE YOURSELF AND KEEP MOVING",
   "BELIVE IN YOURSELF BECAUSE YOU ARE GREAT",
   "DONT WORRY YOU GOT IT",
   "HAVE FAITH YOU WILL GET FAR IN THIS JOURNEY",
   "GOOOOOOOOOO AND CHANGE THE WORLD",
   "DONT WORRY YOU GOT IT",
   "YOU CANT GIVE UP NOW",
   "YOU. CAN. DO. IT.",
   "KEEP ON DOIN YOU",
   "YOU CAN DO ANYTHING YOU SET YOUR HEART TO",
   "ITS A BRAND NEW DAY SO KEEP PUSHING",
   "DONT EVER GIVE UP ON YOUR DREAMS",
   "KEEP CHASING YOUR DREAMS" 
]

NOUNS = [
  "HOT STUD",
  "RAY OF SUNSHINE",
  "SMART COOKIE",
  "MAGICAL BEING",
  "SHINY POKEMON CARD",
  "SEXY HUMAN",
  "SWEETHEART",
  "",
  "SWEATYPIE",
  "CUTIEPATOOTIE",
  "DELIGHTFUL DANDELION",
  "PUPPERINO",
  "LOVEABLE PERSON",
  "POT OF GOLD",
  "DIAMOND IN THE ROUGH",
  "ANTHROPOMORPHIC ALIEN",
  "CHEEKY BABY",
  "INSPIRATIONAL LAD",
  "BREATH OF FRESH AIR",
  "FRIENDLY NEIGHBOURHOOD",
  "ALL ENDURING WARRIOR",
  "SENTIENT TEDDYBEAR WITH EXTRA FLUFF"
]

# words used to generate diseases

BODY_PARTS = [
    'eyebrow',
    'elbow',
    'foot',
    'wenis',
    'butt',
    'eyeball',
    'intestine',
    'brain',
    'ossicle',
    'cornea',
    'hand',
    'nostril',
    'head',
    'face',
]

ADJECTIVES = [
    'a nice',
    'a spicy',
    'an available',
    'a fancy',
    'a simple',
    'an elegant',
    'a jittery',
    'a roasted',
    'a plastic',
    'a juicy',
    'an imaginary',
    'a delicate',
    'a tan',
    'a wooden',
    'a tasty',
    'a spiritual',
    'an acidic',
    'an obsolete',
    'a salty',
    'an organic',
    'a bumpy',
    'an innocent',
    'an electric',
    'a windy',
    'a watery',
    'a fiery',
    'an earthy',
]

SUPERLATIVES = [
    'excessive',
    'superfluous',
    'constant',
    'above-average',
    'intense',
    'troublesome',
    'compulsive',
]

SYMPTOMS = [
    'flatulence',
    'laughter',
    'fainting',
    'exhaustion',
    'angst',
    'cynicism',
    'vomiting',
    'nausea',
    'vertigo',
    'dizziness',
    'ringing in the ears',
]
# from https://simple.wikipedia.org/wiki/List_of_colors

COLORS = [
    'Amaranth',
    'Amber',
    'Amethyst',
    'Apricot',
    'Aquamarine',
    'Azure',
    'Baby blue',
    'Beige',
    'Black',
    'Blue',
    'Blue-green',
    'Blue-violet',
    'Blush',
    'Bronze',
    'Brown',
    'Burgundy',
    'Byzantium',
    'Carmine',
    'Cerise',
    'Cerulean',
    'Champagne',
    'Chartreuse green',
    'Chocolate',
    'Cobalt blue',
    'Coffee',
    'Copper',
    'Coral',
    'Crimson',
    'Cyan',
    'Desert sand',
    'Electric blue',
    'Emerald',
    'Erin',
    'Gold',
    'Gray',
    'Green',
    'Harlequin',
    'Indigo',
    'Ivory',
    'Jade',
    'Jungle green',
    'Lavender',
    'Lemon',
    'Lilac',
    'Lime',
    'Magenta',
    'Magenta rose',
    'Maroon',
    'Mauve',
    'Navy blue',
    'Ocher',
    'Olive',
    'Orange',
    'Orange-red',
    'Orchid',
    'Peach',
    'Pear',
    'Periwinkle',
    'Persian blue',
    'Pink',
    'Plum',
    'Prussian blue',
    'Puce',
    'Purple',
    'Raspberry',
    'Red',
    'Red-violet',
    'Rose',
    'Ruby',
    'Salmon',
    'Sangria',
    'Sapphire',
    'Scarlet',
    'Silver',
    'Slate gray',
    'Spring bud',
    'Spring green',
    'Tan',
    'Taupe',
    'Teal',
    'Turquoise',
    'Violet',
    'Viridian',
    'White',
    'Yellow',
]
