# temporary tests from previous script
# I am a {adj} of {n}, seeking the {color} mayfly

TEST_PHRASES = [
  '"I am a {} {}, seeking the {} mayfly called {}." - SODEEPBOT'
]

ADJECTIVES = [
    'nice',
    'spicy',
    'available',
    'fancy',
    'simple',
    'elegant',
    'jittery',
    'roasted',
    'plastic',
    'juicy',
    'imaginary',
    'delicate',
    'tan',
    'wooden',
    'tasty',
    'spiritual',
    'acidic',
    'obsolete',
    'salty',
    'organic',
    'bumpy',
    'innocent',
    'electric',
    'windy',
    'watery',
    'fiery',
    'earthy'
]

NOUNS = [
    'flame',
    'pie',
    'cakes',
    'fear',
    'potato',
    'harmony',
    'knowledge',
    'society',
    'rabbits',
    'wealth',
    'humor',
    'songs',
    'battle',
    'bubbles',
    'thrones',
    'land',
    'love',
    'unity',
    'respect',
    'power',
    'desire',
    'courage',
    'honesty',
    'loyalty',
    'peace',
    'tomato',
    'rock',
    'birthday',
    'coil',
    'monkey',
    'waves',
    'wax',
    'debt',
    'jellyfish',
    'tree',
    'sharpie',
    'crab',
    'ocean',
    'volleyball',
    'swan',
    'printer',
    'ornament',
    'frames'
]

SUPERLATIVES = [
    'excessive',
    'superfluous',
    'constant',
    'above-average',
    'intense',
    'troublesome',
    'compulsive',
]

# from https://simple.wikipedia.org/wiki/List_of_colors

COLORS = [
    'amaranth',
    'amber',
    'amethyst',
    'apricot',
    'aquamarine',
    'azure',
    'baby blue',
    'beige',
    'black',
    'blue',
    'blue-green',
    'blue-violet',
    'blush',
    'bronze',
    'brown',
    'burgundy',
    'byzantium',
    'carmine',
    'cerise',
    'cerulean',
    'champagne',
    'chartreuse green',
    'chocolate',
    'cobalt blue',
    'coffee',
    'copper',
    'coral',
    'crimson',
    'cyan',
    'desert sand',
    'electric blue',
    'emerald',
    'erin',
    'gold',
    'gray',
    'Green',
    'harlequin',
    'indigo',
    'ivory',
    'jade',
    'jungle green',
    'lavender',
    'lemon',
    'lilac',
    'lime',
    'magenta',
    'magenta rose',
    'maroon',
    'mauve',
    'navy blue',
    'ocher',
    'olive',
    'orange',
    'orange-red',
    'orchid',
    'peach',
    'pear',
    'periwinkle',
    'persian blue',
    'pink',
    'plum',
    'prussian blue',
    'puce',
    'purple',
    'raspberry',
    'red',
    'red-violet',
    'rose',
    'ruby',
    'salmon',
    'sangria',
    'sapphire',
    'scarlet',
    'silver',
    'slate gray',
    'spring bud',
    'spring green',
    'tan',
    'taupe',
    'Teal',
    'turquoise',
    'violet',
    'viridian',
    'white',
    'yellow',
]
