# string templates

QUESTIONS = [
  'Are you suffering from {}?',
  'Are you plagued by {}?',
  'Is {} keeping you up at night?',
  'Worried you might have {}?',
  'You don\'t have to deal with {} alone.',
]

ANSWERS = [
    u'Ask your doctor about {}\u00AE today!',
    u'Try {}\u00AE!',
    u'{}\u00AE can help!',
    u'Ask your doctor if {}\u00AE is right for you!',
]

# words used to generate diseases

BODY_PARTS = [
    'eyebrow',
    'elbow',
    'foot',
    'wenis',
    'butt',
    'eyeball',
    'intestine',
    'brain',
    'ossicle',
    'cornea',
    'hand',
    'nostril',
    'head',
    'face',
]

ADJECTIVES = [
    'nice',
    'spicy',
    'available',
    'fancy',
    'simple',
    'elegant',
    'jittery',
    'roasted',
    'plastic',
    'juicy',
    'imaginary',
    'delicate',
    'tan',
    'wooden',
    'tasty',
    'spiritual',
    'acidic',
    'obsolete',
    'salty',
    'organic',
    'bumpy',
    'innocent',
    'electric',
    'windy',
    'watery',
    'fiery',
    'earthy',
]

SUPERLATIVES = [
    'excessive',
    'superfluous',
    'constant',
    'above-average',
    'intense',
    'troublesome',
    'compulsive',
]

SYMPTOMS = [
    'flatulence',
    'laughter',
    'fainting',
    'exhaustion',
    'angst',
    'cynicism',
    'vomiting',
    'nausea',
    'vertigo',
    'dizziness',
    'ringing in the ears',
]
# from https://simple.wikipedia.org/wiki/List_of_colors

COLORS = [
    'Amaranth',
    'Amber',
    'Amethyst',
    'Apricot',
    'Aquamarine',
    'Azure',
    'Baby blue',
    'Beige',
    'Black',
    'Blue',
    'Blue-green',
    'Blue-violet',
    'Blush',
    'Bronze',
    'Brown',
    'Burgundy',
    'Byzantium',
    'Carmine',
    'Cerise',
    'Cerulean',
    'Champagne',
    'Chartreuse green',
    'Chocolate',
    'Cobalt blue',
    'Coffee',
    'Copper',
    'Coral',
    'Crimson',
    'Cyan',
    'Desert sand',
    'Electric blue',
    'Emerald',
    'Erin',
    'Gold',
    'Gray',
    'Green',
    'Harlequin',
    'Indigo',
    'Ivory',
    'Jade',
    'Jungle green',
    'Lavender',
    'Lemon',
    'Lilac',
    'Lime',
    'Magenta',
    'Magenta rose',
    'Maroon',
    'Mauve',
    'Navy blue',
    'Ocher',
    'Olive',
    'Orange',
    'Orange-red',
    'Orchid',
    'Peach',
    'Pear',
    'Periwinkle',
    'Persian blue',
    'Pink',
    'Plum',
    'Prussian blue',
    'Puce',
    'Purple',
    'Raspberry',
    'Red',
    'Red-violet',
    'Rose',
    'Ruby',
    'Salmon',
    'Sangria',
    'Sapphire',
    'Scarlet',
    'Silver',
    'Slate gray',
    'Spring bud',
    'Spring green',
    'Tan',
    'Taupe',
    'Teal',
    'Turquoise',
    'Violet',
    'Viridian',
    'White',
    'Yellow',
]
